export { default as AboutSection } from "./AboutSection/AboutSection";
export { default as BenefitsSection } from "./BenefitsSection/BenefitsSection";
export { default as Navigation } from "./Navigation/Navigation";
export { default as Header } from "./Header/Header";
export { default as HowItWorksSection } from "./HowItWorksSection/HowItWorksSection";
export { default as ProductSection } from "./ProductSection/ProductSection";
export { default as SupportSection } from "./SupportSection/SupportSection";
export { default as VideoSection } from "./VideoSection/VideoSection";
export { default as Footer } from "./Footer/Footer";
